mini_symfony:
  debug:
    container_dump_path: '%kernel.cache_dir%/%kernel.container_class%.xml'
    debugbar:
      enabled: true
      # Vendor files are included by default, but can be set to false.
      # This can also be set to 'js' or 'css', to only include javascript or css vendor files.
      # Vendor files are for css: font-awesome (including fonts) and highlight.js (css files)
      # and for js: jquery and and highlight.js
      # So if you want syntax highlighting, set it to true.
      # jQuery is set to not conflict with existing jQuery scripts.
      include_vendors: true

      # The Debugbar can capture Ajax requests and display them. If you don't want this (ie. because of errors),
      # you can use this option to disable sending the data through the headers.
      capture_ajax: true

      # The Debugbar can emulate the Clockwork headers, so you can use the Chrome
      # Extension, without the server-side code. It uses Debugbar collectors instead.
      clockwork: false

      # Enable/disable DataCollectors
      collectors:
        events: true
        exceptions: true
        request: true
        routing: true
        phpinfo: true
        time: true
        memory: true
        queries: true

      # Configure some DataCollectors
      options:
        queries:
          with_params: true # Render SQL with the parameters substituted
          timeline: false # Add the queries to the timeline
          backtrace: false
          explain:
            enabled: false
            type:
              - SELECT # SELECT, INSERT, UPDATE, DELETE for MySQL 5.6.3+
          hints: true # Show hints for common mistakes
        routing:
          label: true

      route_prifix: _debugbar