mini_symfony:
  debug:
    container_dump_path: '%kernel.cache_dir%/%kernel.container_class%.xml'
    debugbar:
      enabled: false
      collectors:
        request: false
        phpinfo: false
        time: false
        memory: false