mini_symfony:
  debug:
    container_dump_path: '%kernel.cache_dir%/%kernel.container_class%.xml'
    debugbar:
      enabled: true
      collectors:
        events: true
        request: true
        phpinfo: true
        time: true
        memory: true
        db: false