parameters:
    debug.container.dump: %kernel.cache_dir%/%kernel.container_class%.xml

services:
    debug_command:
      class: MiniSymfony\CompanionBundle\Command\ContainerDebugCommand
      tags:
          - { name: console.command }

    # Controllers
    controller.asset:
      class: MiniSymfony\CompanionBundle\Controllers\AssetController
      arguments:
        - '@debugbar'
        - '@router'

    # Debugbar
    debugbar.request_subscriber:
        class: MiniSymfony\CompanionBundle\EventSubscribers\RequestEventSubscriber
        arguments:
          - '@debugbar'
        tags:
            - { name: kernel.event_subscriber }