parameters:
    debug.container.dump: %kernel.cache_dir%/%kernel.container_class%.xml

services:
    debug_command:
      class: MiniSymfony\CompanionBundle\Command\ContainerDebugCommand
      tags:
          - { name: console.command }

    debug.event_data_collector:
      class: MiniSymfony\CompanionBundle\DebugBar\DataCollector\EventCollector
      arguments:
        - ~
        - '@event_dispatcher'
      tags:
        - { name: kernel.event_listener, event: '#', method: 'onWildcardEvent' }

    companion.event_dispatcher:
        class: MiniSymfony\CompanionBundle\EventDispatcher\ContainerAwareEventDispatcher
        arguments:
            - '@service_container'
            - '@companion.event_dispatcher.inner'

    # Controllers
    controller.asset:
      class: MiniSymfony\CompanionBundle\Controllers\AssetController
      arguments:
        - '@debugbar'
        - '@router'

    # Debugbar
    debugbar.request_subscriber:
        class: MiniSymfony\CompanionBundle\EventSubscribers\RequestEventSubscriber
        arguments:
          - '@debugbar'
          - '@event_dispatcher'
        tags:
            - { name: kernel.event_subscriber }